apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
        name: onlinemarriagecounsel-com-tls
spec:
        secretName: onlinemarriagecounsel-com
        issuerRef:
                name: letsencrypt-prod
                kind: ClusterIssuer
        commonName: onlinemarriagecounsel.com
        dnsNames:
                - onlinemarriagecounsel.com
                - www.onlinemarriagecounsel.com
